# -*- coding: utf-8 -*-
"""Question_one_chrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZg7S9Gk89t-K15ddVXEoxzCcqfGxPUI
"""

import re

str="""
{"orders":[{"id":1},{"id":2},{"id":3},{"id":4},{"id":5},{"id":6},{"id":7},{"id":8},{"id":9},{"id":10},{"id":11},{"i
d":648},{"id":649},{"id":650},{"id":651},{"id":652},{"id":653}],"errors":[{"code":3,"message":"[PHP
Warning #2]
"""

"""def getNumbers(str):
    array = re.findall(r':[0-9]+', str)
    return array"""

#array = getNumbers(str)
#print(*array)

match = re.findall(r':[0-9]+', str)
for i in range(0,len(match)):
  print(match[i][1:])